<div class="section">

	<div class="container">

		<div class="row">

			<?php

				if (isset($quizSubmitSuccess) && $quizSubmitSuccess) {

					echo '<div class="alert alert-success">Successfully submit answers for quiz.</div>';

				}

			?>

			<div class="col-sm-6 col-md-5 col-lg-5">

				<img src="<?php echo base_url(); ?>img/img6.png" class="center-block img-responsive margin-top-custom">

			</div>

			<div class="col-sm-6 col-md-7 col-lg-7">

				<h1>Online Quiz</h1>

				<p>Not happy with your current results? Failed once in your test? Fret not, try again and again until

					you succeed. With customized questions framed in different difficulty levels, every student can

					repeatedly attempt their areas of weaknesses by just a few clicks. Endless questions will be

					generated to suit each one’s needs. With SmartJen easy-to-use online quiz, we make sure your child

					learn from their mistakes by keeping track of their progresses. Every single step taken is recorded

					and self-generated by our automated system until they reach perfect score. Nothing more than

					practices make perfect scorers.</p>

			</div>

		</div>

	</div>

</div>



<div class="section">

	<div class="container">

		<div class="row">

		<?php 

		if (isset($quizError) && $quizError) {

		echo '<div class="alert alert-danger">';

		echo $quizErrorMessage;

		echo '</div>';

		

		} else {

		?>
		<div class="profile_div">
		<div class="profile_div_header">
		<h4>My Quizzes</h4>
		</div>
		
		<div id="quiz-tab" class="tab-container tab-success">
		<ul class="nav quiz-tabs">
		<li class="quizz-tab col-sm-6 col-md-6 col-lg-6 active" style="text-align:center;padding-left:0px;padding-right:0px;">
		<a href="#quiz_0" id="onlinequiz_tab" data-toggle="tab" data-lang="outstanding">My Outstanding Quizzes</a>
		</li>
		<li class="quizz-tab col-sm-6 col-md-6 col-lg-6" style="text-align:center;padding-left:0px;padding-right:0px;">
		<a href="#quiz_1" data-toggle="tab" data-lang="completed">My Completed Quizzes</a>
		</li>
		</ul>
		
		<div class="tab-content quiz-content">
		<!-- <div class="tab-pane active clearfix" id="quiz_0"><span class="fa fa-spin fa-spinner"></span> Loading...</div> -->
		</div>
		</div>
		</div>
		</div>
		

		<?php
		}

		?>

		</div>
	</div>
</div>

<script type="text/javascript">



function get_quizzes(pageno, status) {

	$.ajax({
		url: '<?php echo base_url();?>onlinequiz/get_quiz_content_student/' + pageno + '/' + status,
	}).done(function (html) {
		$('.quiz-content').html(html);
	});
}

$(document).ready(function() {
	var pageno = 1;
	var status = "outstanding";
	get_quizzes(pageno, status);
	
	$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
		var pageno = 1;
		var status = $(e.target).data("lang");
		get_quizzes(pageno, status);
	});
	
	$('body').on('click','.page-link a',function(e){
		e.preventDefault();
		pageno = $(this).attr('data-ci-pagination-page');
		get_quizzes(pageno, 'outstanding');
	});
	
	$('#showHistoricalAttempts').on('click', function(e){
		e.preventDefault();
		if ($(this).text() == "Show Attempt History") {
			$(this).closest("tr").nextAll('.attemptHistory').first().show("slow");
			$(this).text("Hide Attempt History");
		} else 
		if ($(this).text() == "Hide Attempt History") {
			$(this).closest("tr").nextAll('.attemptHistory').first().hide("slow");
			$(this).text("Show Attempt History");
		}
	});
});
</script>

